title: mfirry
description: Marco's personal page
baseurl: ""
url: "https://mfirry.github.io"
github_username: mfirry
linkedin_username: mfirry

# Build settings
theme: minima
plugins:
  - jekyll-feed
